# https://docs.docker.com/compose/compose-file/

services:
  ansible-dev:
    container_name: ansible-dev
    build:
      context: .
      dockerfile: ansible/Dockerfile
    networks:
      - dev-backend
    volumes:
      - ./ansible/etc-ansible-config:/etc/ansible/
      - ./web/etc-php-8.2-apache2-conf.d:/etc/ansible/web/etc-php-8.2-apache2-conf.d
      - ./sysadmin-ssh-keys/rsa_sysadmin:/home/sysadmin/.ssh/id_rsa:ro
      - ./sysadmin-ssh-keys/rsa_sysadmin.pub:/home/sysadmin/.ssh/id_rsa.pub:ro
      - ./sysadmin-ssh-keys/rsa_sysadmin.pub:/home/sysadmin/.ssh/authorized_keys:ro
    ports:
      - "22001:22"
    environment:
      - USER=sysadmin

  web-dev:
    container_name: web-dev
    depends_on:
      - db-dev
    build:
      args:
        WP_VERSION: ${WP_VERSION:?have you copied .env.example to .env?}
      context: .
      dockerfile: web/Dockerfile
    networks:
      - dev-backend
    environment:
      USER: sysadmin
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db-dev
      PMA_PORT: 3306
      WORDPRESS_CONFIG_EXTRA: |
        # Use dispatch port by default
        if ('${CODESPACE_NAME:-}') {
          define('WP_HOME', 'https://${CODESPACE_NAME:-}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-}');
        } else {
          define('WP_HOME', 'http://localhost:8080');
          define('WP_SITEURL', 'http://localhost:8080');
        }
      WORDPRESS_DB_HOST: db-dev:3306
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_USER: root
    init: true
    ports:
      - '8080:80'
      - '22002:22'
    restart: on-failure
    volumes:
      - ./web/etc-apache2-sites-available:/etc/apache2/sites-available
      - wp-data:/var/www/dev
      - ./sysadmin-ssh-keys/rsa_sysadmin:/home/sysadmin/.ssh/id_rsa:ro
      - ./sysadmin-ssh-keys/rsa_sysadmin.pub:/home/sysadmin/.ssh/id_rsa.pub:ro
      - ./sysadmin-ssh-keys/rsa_sysadmin.pub:/home/sysadmin/.ssh/authorized_keys:ro

  db-dev:
    container_name: db-dev
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    image: mariadb
    networks:
      - dev-backend
    restart: on-failure
    volumes:
      - db-data:/var/lib/mysql

  bastion-dev:
    container_name: bastion-dev
    build:
      context: .
      dockerfile: bastion/Dockerfile
    networks:
      - dev-backend
    expose:
      - 22/tcp
    ports:
      - 22222:22/tcp
    volumes:
      - ./sysadmin-ssh-keys/rsa_sysadmin:/home/sysadmin/.ssh/id_rsa:ro
      - ./sysadmin-ssh-keys/rsa_sysadmin.pub:/home/sysadmin/.ssh/id_rsa.pub:ro
      - ./sysadmin-ssh-keys/rsa_sysadmin.pub:/home/sysadmin/.ssh/authorized_keys:ro

volumes:
  db-data:
    name: db-data
  wp-data:
    name: wp-data

networks:
  dev-backend:
    name: dev-backend
    driver: bridge

